gotta start somewher
egormoroz/tsetnoc pull request #1
Opened 2024-07-04 14:17 UTC by egormoroz

will add more later (probably)

2024-07-04 21:04 UTC, L1mple requested changes
Overall кстати прям хорошо получилось, сущности в БД хорошо спроектировал, тэги для проверки ответа интересные

2024-07-04 21:04 UTC, L1mple commented on requirements.txt
> +# sqlalchemy==2.0.31
А чего закомментил?

Вообще можно в сторону poetry посмотреть для управления зависимостями, кажется к нему много где уже пришли

2024-07-04 21:04 UTC, L1mple commented on tables.md
> +9. ContestSubmision
Кажется у Submission и Contest отношение One2Many, т.к. конкретное решение связано с конкретной задачкой -> максимум с 1 контестом(в рамках которого решалась задачка)?

И вроде эта табличка тогда не нужна

2024-07-04 21:04 UTC, L1mple commented on app/core/process.py
> +        assert sub.verdict == Verdict.PENDING
Такие штуки обычно решаются на уровне контракта API (валидации Pydantic-a)

2024-07-04 21:04 UTC, L1mple commented on app/core/process.py
> +    def _get_problem(self, sub: Submission) -> Problem | None:
Кажется эта функция делает слишком много (кажется нарушается SRP из принципов SOLID-a), семантически она называется получение проблемы, но при этом получает почти все остальные связанные с решением сущности и еще сразу же проверяет решение на валидность по своим правилам

Стоит проверку делать отдельно

2024-07-04 21:04 UTC, L1mple commented on app/core/process.py
> +            return
А пользователь сможет узнать, что пошло не так при отправке решения?

2024-07-04 21:04 UTC, L1mple commented on app/core/process.py
> +def _compare_answers(a: Answer, b: Answer, tags: Set[int]) -> Verdict:
А почему последние 2 функции не в классе?

Они же вроде относятся к обработке решения?

2024-07-04 21:04 UTC, L1mple commented on app/core/process.py
> +def is_submission_valid(
Вообще нам можно не делать 4 отдельных запроса к БД, только чтобы проверить валидность решения. Если эти колонки в базе данных будут заданы как ForeignKey, то тебе БД физически не даст создать такую запись, поэтому можно просто ловить ошибку при попытке создания сущности в БД

2024-07-04 21:59 UTC, egormoroz commented on requirements.txt
> +# sqlalchemy==2.0.31
Закомментил, т.к. привык добавлять зависимости по мере их использования; а тут я пока что использую питон без всего. В этом нет какого-то высокого смысла, прост так делаю обычно)
Насчёт poetry посмотрю, мб в этой штуке как раз буду его и использовать в будущем. Звучит лучше, чем руками писать версии в текстовый файл хах

2024-07-04 22:05 UTC, egormoroz commented on tables.md
> +9. ContestSubmision
Звучит логично, да. Я просто изначально думал, что можно сделать глобальный пул/архив задач, куда отправляются задачки с прошедших контестов. И тогда типо решение может быть вообще не принадлежать к контесту. 
Но сейчас так подумал, что будет проще этот глобальный пул считать вечным контестов с нулевым индекс или типо того, и тогда неоднозначности не возникает. И тогда да, эта табличка оказывается лишней...

2024-07-04 22:12 UTC, egormoroz commented on app/core/process.py
> +        assert sub.verdict == Verdict.PENDING
Ну вообще да, просто я тут добавил ассерт, т.к. это типо как внутренний программный инвариант. И если он ломается, то вызывающий делает что-то не так. То есть ошибка программиста (меня в будущем, условно), передающего не то, что ожидается. В идеале мечтаю, чтобы этот ассерт можно вообще статически проверять линтером или типо того.
А pydantic, наскок понимаю, это уже для рантайма проверить что нам такое прилетело от юзера. 
Я вообще думаю, что я немного неудачно выбрал примитивы. Типо у меня есть два решения:
- которое только что прислали и надо проверить
- которое уже проверено и лежит в бд
Класс Submission эти два примитива неловко объединяет. И типо на вход в функцию process прилетает первый тип, а на выходе она даёт вердикт и второй тип (если всё окей). Ассерт тут как раз проверяет, что нам на вход подали первый тип решения. Я всё ещё думаю, стоит ли оставить один Submission или сделать два почти одинаковых. Пока думаю, оно того не стоит....

2024-07-04 22:14 UTC, egormoroz commented on app/core/process.py
> +    def _get_problem(self, sub: Submission) -> Problem | None:
Тут со смыслом, да

2024-07-04 22:18 UTC, egormoroz commented on app/core/process.py
> +            return
Согласен, нормальные ошибки это круто. Думаешь, получится отделаться просто несколькими новыми кодами ошибок? Мб просто в вердикт добавить новые константы:
- задача по индексу не существует в контексте
- контест по индексу не существует
- юзера нет в контексте
- и тд

2024-07-04 22:22 UTC, egormoroz commented on app/core/process.py
> +def _compare_answers(a: Answer, b: Answer, tags: Set[int]) -> Verdict:
Я думал будет хорошей идеей делать максимально изолированные функции/сущности. А у метода класса будет доступ к интерфейсам бд, хоть он ими и не пользуется. Хотя с этой точки зрения можно тогда сделать метод статическим наверное...
А так да, кроме этого особых причин нет, как минимум проверку на валидность можно бы и сделать методом

2024-07-04 22:25 UTC, egormoroz commented on app/core/process.py
> +def is_submission_valid(
Это со смыслом. Я просто думал, что у меня реализации интерфейсов будут обмазаны кэшами, и типо 4 вызова в среднем улетят в кэши, поэтому не страшно... 
А вообще про то, что ошибка всплывёт при попытки создании сущности в бд, не подумал. Звучит рил проще и солиднее

2024-07-07 17:10 UTC, L1mple commented on app/core/process.py
> +        assert sub.verdict == Verdict.PENDING
Обычно делают 2 почти одинаковых, общие поля выделяют в отдельную модель(класс) и потом от неё наследуют отличающиеся

2024-07-07 17:10 UTC, L1mple commented on app/core/process.py
> +            return
В целом можно на уровне API возвращать 400ку, а в её теле давать код и описание того, что пошло не так, как вариант можно добавить их в вердикт, звучит логично

2024-07-07 17:10 UTC, L1mple commented on app/core/process.py
> +def _compare_answers(a: Answer, b: Answer, tags: Set[int]) -> Verdict:
Да, обычно такие методы делают статическими, но всё равно как часть класса, т.к. они используются в логике процессинга

2024-07-15 20:44 UTC, L1mple approved these changes
LGTM!

2024-07-15 20:50 UTC, merged