FastAPI endpoints, should theoretically work???
egormoroz/tsetnoc pull request #2
Opened 2024-07-15 14:43 UTC by egormoroz

Чувствую наговнокодил жестка

2024-07-15 21:34 UTC, L1mple requested changes

2024-07-15 21:34 UTC, L1mple commented on app/api/dependencies.py
> +from app.common.interfaces import (
Стоит посмотреть в сторону Dependency Injection фреймворков, таких как Dependency Injector или dishka, т.к. в реальных проектах скорее всего именно они будут использоваться

2024-07-15 21:34 UTC, L1mple commented on app/api/endpoints.py
> +        return AddedDTO(ids=[u.id])
Как вариант можно возвращать код 201 и Location Header:
`Location: yourdomain.com/user/{u.id}`
По которому можно будет увидеть профиль пользователя

2024-07-15 21:34 UTC, L1mple commented on app/api/endpoints.py
> +@router.post("/join")
Если ты ничего не отдаешь клиенту, то по идее надо 204 код возвращать, чтобы твои коллеги с фронтэнда не ругались из-за того, что у них автогенерация клиентского кода по твоей openapi доке не работает:D

2024-07-15 21:34 UTC, L1mple commented on app/api/endpoints.py
> +@router.post("/addproblems")
По идее, если у нас REST, то можно путь оставить `/problems`, а метод POST сам показывает, что это именно создание объектов

2024-07-15 21:34 UTC, L1mple commented on app/common/interfaces/composite.py
> +# Implementations of various complex queries that might require some optimization
Почему бы сразу не сделать их оптимизированными в оригинальных репозиториях?

В этом по идее ничего плохого нет

2024-07-15 21:34 UTC, L1mple commented on app/api/endpoints.py
> +async def get_submissionlist(
На сам код это не особо влияет, но в питоне snake casом каждое слово разделяют, примерно так будет
```suggestion
async def get_submission_list(
```

2024-07-15 21:34 UTC, L1mple commented on app/api/endpoints.py
> +        subsrv: SubServerFB):
По идее это всё можно завернуть в репозиторий submissions или problems (смотря что у нас считается доменным агрегатом)

2024-07-15 21:46 UTC, egormoroz commented on app/common/interfaces/composite.py
> +# Implementations of various complex queries that might require some optimization
Да у меня какой-то паразит в голове утверждал, что можно только один репозиторий на таблицу. И с такой дурацкой логикой если бы я начал делать отдельные специализированные методы, то репозиторий IContestRepo надулся бы до катастрофических размеров, его реализация обречена стать мегаклассом в 1кк строк.
А надо рил одну репу на один unit of work, и делать специализированные репы где надо. И тогда никаких мегаклассов не возникает, много раздельных специалистов.

2024-07-15 21:49 UTC, egormoroz commented on app/common/interfaces/composite.py
> +# Implementations of various complex queries that might require some optimization
Ну и на этой ноте, надо бы этот IContestRepo уже прямо щас разбить на интерфейсы поменьше

2024-07-15 21:51 UTC, egormoroz commented on app/api/endpoints.py
> +        subsrv: SubServerFB):
Заверну в submissions скорее всего

2024-07-16 12:06 UTC, egormoroz commented on app/api/endpoints.py
> +        return AddedDTO(ids=[u.id])
Вообще, там чуть ниже есть endpoint для добавления задач булком, и в нём уже, насколько я понимаю, в location кучу индексов не запихнуть и придётся возвращать json. Мб для единообразия стоит тут так же оставить? Единственное, я думаю теперь везде возвращать сверху сообщение об успехе.
Ну и тогда можно тупо сделать тут: `return { "message": "user created successfully", "id": f"{u.id}"  }`

2024-07-16 13:29 UTC, egormoroz commented on app/api/dependencies.py
> +from app.common.interfaces import (
Ладно, я пока отложу это в (((долгий))) ящик, и пока сделаю просто bootstrap штуку, которая сделает всю работу...

2024-07-16 20:56 UTC, egormoroz commented on app/api/dependencies.py
> +from app.common.interfaces import (
Блен, я так подумал, мб в этом проекте хватит FastAPIшного через `Depends` + того костыля в виде синглтона `Bootstrap`? (app/bootstrap.py + app/api/dependencies.py его юзает)...

2024-07-19 07:50 UTC, closed without merging